//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecursosHumanos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salida_Empleados
    {
        public int Id { get; set; }
        public int Empleado_ID { get; set; }
        public int Tipo_Salida_ID { get; set; }
        public string Motivo { get; set; }
        public System.DateTime Fecha_Salida { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_Salida Tipo_Salida { get; set; }
    }
}
